import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { unstable_ViewTransition as ViewTransition } from "react";
import { NavigationMenu } from "@/components/NavigationMenu";
import { MobileNav } from "@/components/MobileNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ViewTransition>
          <ThemeProvider>
            <div className="flex flex-col min-h-screen">
              <div className="w-full flex justify-end p-4">
                <NavigationMenu className="hidden md:flex" />
                <MobileNav />
              </div>
              <div className="flex-1 flex flex-col">{children}</div>
            </div>
          </ThemeProvider>
        </ViewTransition>
      </body>
    </html>
  );
}
